# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: dreamweaverdb
  pool: 5

test:
  adapter: postgresql
  database: dreamweaverdb
  pool: 5

production:
  adapter: postgresql
  database: dreamweaverdb
  pool: 5